name: Windows

on:
  push:
    paths:
      - "CMakeLists.txt"
      - "**/workflows/build_windows.yml"
      - "**/cmake/**"
      - "**/examples/**"
      - "**/modules/**"
      - "**/tests/**"
      - "**/thirdparty/**"
      - "!**/native/*_android.*"
      - "!**/native/*_apple.*"
      - "!**/native/*_emscripten.*"
      - "!**/native/*_linux.*"
      - "!**/native/*_ios.*"
      - "!**/native/*_mac.*"
      - "!**/native/*_posix.*"
      - "!**/native/*_wasm.*"
    branches:
      - "**"

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - uses: seanmiddleditch/gha-setup-ninja@master

    - name: Create Build Environment
      run: cmake -E make_directory ${{runner.workspace}}/build

    - name: Configure
      working-directory: ${{runner.workspace}}/build
      run: cmake ${{ github.workspace }} -DYUP_ENABLE_TESTS=ON -DYUP_ENABLE_EXAMPLES=ON

    - name: Build Tests Debug
      working-directory: ${{runner.workspace}}/build
      run: cmake --build . --config Debug --parallel 4 --target yup_tests

    - name: Execute Tests Debug
      working-directory: ${{runner.workspace}}/build/tests/Debug
      run: ./yup_tests.exe

    - name: Build Tests Release
      working-directory: ${{runner.workspace}}/build
      run: cmake --build . --config Release --parallel 4 --target yup_tests

    - name: Execute Tests Release
      working-directory: ${{runner.workspace}}/build/tests/Release
      run: ./yup_tests.exe

    - name: Build Examples Debug
      working-directory: ${{runner.workspace}}/build
      run: |
        cmake --build . --config Debug --parallel 4 --target example_console
        cmake --build . --config Debug --parallel 4 --target example_app
        cmake --build . --config Debug --parallel 4 --target example_graphics
        cmake --build . --config Debug --parallel 4 --target example_render
        cmake --build . --config Debug --parallel 4 --target example_plugin

    - name: Build Examples Release
      working-directory: ${{runner.workspace}}/build
      run: |
        cmake --build . --config Release --parallel 4 --target example_console
        cmake --build . --config Release --parallel 4 --target example_app
        cmake --build . --config Release --parallel 4 --target example_graphics
        cmake --build . --config Release --parallel 4 --target example_render
        cmake --build . --config Release --parallel 4 --target example_plugin
