name: Linux

on:
  push:
    paths:
      - "CMakeLists.txt"
      - "**/workflows/build_linux.yml"
      - "**/cmake/**"
      - "**/examples/**"
      - "**/modules/**"
      - "**/tests/**"
      - "**/thirdparty/**"
      - "!**/native/*_android.*"
      - "!**/native/*_emscripten.*"
      - "!**/native/*_ios.*"
      - "!**/native/*_mac.*"
      - "!**/native/*_wasm.*"
      - "!**/native/*_windows.*"
    branches:
      - "**"

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - uses: seanmiddleditch/gha-setup-ninja@master

    - name: Install Dependencies
      run: |
        sudo apt-get update && sudo apt-get install -y \
        libasound2-dev libjack-jackd2-dev ladspa-sdk libcurl4-openssl-dev libfreetype6-dev \
        libx11-dev libxcomposite-dev libxcursor-dev libxcursor-dev libxext-dev libxi-dev libxinerama-dev \
        libxrandr-dev libxrender-dev libglu1-mesa-dev mesa-common-dev

    - name: Create Build Environment
      run: cmake -E make_directory ${{runner.workspace}}/build

    - name: Configure
      working-directory: ${{runner.workspace}}/build
      run: cmake $GITHUB_WORKSPACE -G "Ninja Multi-Config" -DYUP_ENABLE_TESTS=ON -DYUP_ENABLE_EXAMPLES=ON

    - name: Build Debug
      working-directory: ${{runner.workspace}}/build
      run: |
        cmake --build . --config Debug --parallel 4 --target yup_tests
        cmake --build . --config Debug --parallel 4 --target example_console
        cmake --build . --config Debug --parallel 4 --target example_app
        cmake --build . --config Debug --parallel 4 --target example_graphics
        cmake --build . --config Debug --parallel 4 --target example_render
        cmake --build . --config Debug --parallel 4 --target example_plugin

    - name: Test Debug
      working-directory: ${{runner.workspace}}/build/tests/Debug
      run: ./yup_tests

    - name: Build Release
      working-directory: ${{runner.workspace}}/build
      run: |
        cmake --build . --config Release --parallel 4 --target yup_tests
        cmake --build . --config Release --parallel 4 --target example_console
        cmake --build . --config Release --parallel 4 --target example_app
        cmake --build . --config Release --parallel 4 --target example_graphics
        cmake --build . --config Release --parallel 4 --target example_render
        cmake --build . --config Release --parallel 4 --target example_plugin

    - name: Test Release
      working-directory: ${{runner.workspace}}/build/tests/Release
      run: ./yup_tests
