name: MacOS

on:
  push:
    paths:
      - "CMakeLists.txt"
      - "**/workflows/build_macos.yml"
      - "**/cmake/**"
      - "**/examples/**"
      - "**/modules/**"
      - "**/tests/**"
      - "**/thirdparty/**"
      - "!**/native/*_android.*"
      - "!**/native/*_emscripten.*"
      - "!**/native/*_linux.*"
      - "!**/native/*_ios.*"
      - "!**/native/*_wasm.*"
      - "!**/native/*_windows.*"
  pull_request:
    branches:
      - "**"

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: macos-latest
    env:
      DEVELOPER_DIR: /Applications/Xcode_15.1.app/Contents/Developer

    steps:
    - uses: actions/checkout@v4

    - name: Create Build Environment
      run: cmake -E make_directory ${{runner.workspace}}/build

    - name: Configure
      working-directory: ${{runner.workspace}}/build
      run: cmake ${{ github.workspace }} -G Xcode -DYUP_ENABLE_TESTS=ON -DYUP_ENABLE_EXAMPLES=ON

    - name: Build Debug
      working-directory: ${{runner.workspace}}/build
      run: |
        cmake --build . --config Debug --parallel 4 --target yup_tests
        cmake --build . --config Debug --parallel 4 --target example_console
        cmake --build . --config Debug --parallel 4 --target example_app
        cmake --build . --config Debug --parallel 4 --target example_graphics
        cmake --build . --config Debug --parallel 4 --target example_render
        cmake --build . --config Debug --parallel 4 --target example_plugin

    - name: Test Debug
      working-directory: ${{runner.workspace}}/build/tests/Debug
      run: ./yup_tests

    - name: Build Release
      working-directory: ${{runner.workspace}}/build
      run: |
        cmake --build . --config Release --parallel 4 --target yup_tests
        cmake --build . --config Release --parallel 4 --target example_console
        cmake --build . --config Release --parallel 4 --target example_app
        cmake --build . --config Release --parallel 4 --target example_graphics
        cmake --build . --config Release --parallel 4 --target example_render
        cmake --build . --config Release --parallel 4 --target example_plugin

    - name: Test Release
      working-directory: ${{runner.workspace}}/build/tests/Release
      run: ./yup_tests
