name: Clang Format

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  format:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Clang Code Formatter
        uses: joaomarcosth9/clang-format-action
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
