name: Clang Format Apply

# run on pull requests to develop
on:
  pull_request:
    branches:
      - main

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 2

      - uses: purduesigbots/clang-format-action@1
        with:
          style: file

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4.1.2
        with:
          commit_message: Apply clang-format changes
          branch: ${{ github.head_ref }}
