name: Clang Format

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  format:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get -y install clang-format
          clang-format --version

      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v44
        with:
          files: |
            **/*.c
            **/*.cpp
            **/*.h
            **/*.hpp
            **/*.mm
            !**/thirdparty/**
            !**/zlib/**
            !**/oboe/**

      - name: Configure repository
        run: |
          git init
          git fetch origin ${GITHUB_REF#*refs/heads/}
          git checkout ${GITHUB_REF#*refs/heads/}
          git config --global user.email "clang-format@1337z.ninja"
          git config --global user.name "Clang Format"
          git update-index --assume-unchanged .github/workflows/*

      - name: Run clang-format
        working-directory: ${{ github.workspace }}
        env:
          ALL_CHANGED_FILES: ${{ steps.changed-files.outputs.all_changed_files }}
        run: |
          echo $ALL_CHANGED_FILES
          clang-format -style=file -i $ALL_CHANGED_FILES
          git status

      #- name: Push changes
      #  run: |
      #    git commit -a -m "Apply code formatting" || true
      #    git push -u origin ${GITHUB_REF#*refs/heads/}
